# Pull a image with node already integrated
FROM node:20-alpine
# Define a directory to use inside the container
WORKDIR /app
# Copy the content of our working directory into
# the container's working directory
COPY package*.json ./
# Install necessary requirements
RUN npm install
#Bundle app source
COPY . .
# Expose port 8080 for the web server
EXPOSE 8080
# Define the command for starting our web application
# inside the container (often app.js)
CMD [ "node", "server.js"]