version: '3.8'

services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.database  # Bygger från din custom Dockerfile
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend  # Bygger frontend från din frontend-Dockerfile
    container_name: node_frontend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgres://postgres:12345@database:5432/postgres"

volumes:
  db_data:
